### ISSUE TITLE
Original source code

### ISSUE THREAD

**Issue by raphaklaus** [binji/pokegb#4]
Hi! Any chance to release the unobfustated code?

**Comment by binji** [comment]
Yeah, I'm working on a write-up w/ some unobfuscated code. I'll link to it when it's ready!

**Comment by binji** [comment]
Here's the write-up: https://binji.github.io/posts/pokegb/
Here's a link to some unobfuscated code: https://gist.github.com/binji/395669d45e9005950232043ab4378abe
