### ISSUE TITLE
Make configurable the A/B buttons

### ISSUE THREAD

**Issue by Chemaclass** [binji/pokegb#6]
## Current Behaviour

Currently, the buttons are set as `"B Button"=Z, "A Button"=X`. 
The problem is that for german keyboards (QWERTZ) the Z and the X are really far away. Instead, next to the X is the Y.

## Acceptance Criteria

Make configurable the A/B buttons, so they can be chosen at compile time via an argument/option .

> Alternative easier/temporal solution: explain (in the docu) where to change it in the code.

**Comment by bastetfurry** [comment]
I second that, or write in the comments where in that obfuscated work of art we can change that. :)

**Comment by binji** [comment]
oh, good point! you can find the keyboard keys here:
https://github.com/binji/pokegb/blob/9c03ea41714b24373a352f75d27b0dc86a5b2250/pokegb.cc#L30

| number | key | gameboy button |
| - | - | - |
| 27 | X | A Button |
| 29 | Z | B Button |
| 43 | Tab | Select Button |
| 40 | Return | Start Button |
| 79 | Arrow Right | DPAD Right |
| 80 | Arrow Left | DPAD Left |
| 81 | Arrow Down | DPAD Down |
| 82 | Arrow Up | DPAD Up |

and here is a list of SDL scancodes you can use to remap:
https://www.libsdl.org/tmp/SDL/include/SDL_scancode.h

**Comment by binji** [comment]
Added this info the main README.md
